apiVersion: v1
kind: Service
metadata:
  name: gorae-judge-service
spec:
  selector:
    app: gorae-judge
  ports:
    - protocol: 'TCP'
      port: 9000
      targetPort: 9000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gorae-judge
  labels:
    app: gorae-judge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gorae-judge
  template:
    metadata:
      labels:
        app: gorae-judge
    spec:
      containers:
        - name: gorae-judge
          image: lifetwoshot/gorae-judge:latest
          imagePullPolicy: Always
          env:
            - name: JUDGE_ADDRESS
              value: "gorae-judge-service.default"
            - name: EUREKA_ADDRESS
              value: "gorae-eureka-service.default"
#          resources:
#            requests:
#              cpu: "10m"
#            limits:
#              cpu: "50m"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30